/**
 *This program is free software: you can redistribute it and/or modify
 *it under the terms of the GNU General Public License as published by
 *the Free Software Foundation, either version 3 of the License, or
 *(at your option) any later version.
 *
 *This program is distributed in the hope that it will be useful,
 *but WITHOUT ANY WARRANTY; without even the implied warranty of
 *MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *GNU General Public License for more details.
 *
 *You should have received a copy of the GNU General Public License
 *along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * GruntDetailsForm.java
 *
 * Created on Oct 13, 2009, 10:37:28 PM
 */
package net.whn.loki.master;

import java.text.DecimalFormat;
import net.whn.loki.common.GruntDetails;
import net.whn.loki.common.LokiForm;

/**
 *
 * @author daniel
 */
public class GruntDetailsForm extends LokiForm {

    /** Creates new form GruntDetailsForm */
    public GruntDetailsForm(GruntDetails d) {
        initComponents();
        if (d != null) {
            setTitle("Grunt details for '" + d.getHostname() + "'");
            lblOSName.setText(d.getOsName());
            lblOSVersion.setText(d.getOsVersion());
            lblOSArch.setText(d.getOsArchitecture());
            lblCores.setText(Integer.toString(d.getProcessors()));
            lblMemory.setText(readableMemory(d.getTotalMemory()) + " GB");
            lblSwapMemory.setText(readableMemory(d.getTotalSwap()) + " GB");
            lblUserName.setText(d.getUserName());
            lblHomeDir.setText(d.getUserHome());
            lblWorkingDir.setText(d.getCurrentWorkingDir());
        }
    }

    /*PRIVATE*/
    private String readableMemory(long memory) {
        DecimalFormat fmt = new DecimalFormat("#0.00");
        final long bytesPerGB = 1073741824;
        double result = (double) memory / (double) bytesPerGB;
        return fmt.format(result);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblOSName = new javax.swing.JLabel();
        lblOSVersion = new javax.swing.JLabel();
        lblOSArch = new javax.swing.JLabel();
        pnlResources = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCores = new javax.swing.JLabel();
        lblMemory = new javax.swing.JLabel();
        lblSwapMemory = new javax.swing.JLabel();
        pnlEnvironment = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblHomeDir = new javax.swing.JLabel();
        lblWorkingDir = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grunt Details");

        pnlOS.setBorder(javax.swing.BorderFactory.createTitledBorder("Operating System"));

        jLabel1.setText("name:");

        jLabel2.setText("version:");

        jLabel3.setText("architecture:");

        javax.swing.GroupLayout pnlOSLayout = new javax.swing.GroupLayout(pnlOS);
        pnlOS.setLayout(pnlOSLayout);
        pnlOSLayout.setHorizontalGroup(
            pnlOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOSLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(pnlOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOSName)
                    .addComponent(lblOSVersion)
                    .addComponent(lblOSArch))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        pnlOSLayout.setVerticalGroup(
            pnlOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOSLayout.createSequentialGroup()
                .addGroup(pnlOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblOSName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblOSVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblOSArch))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlResources.setBorder(javax.swing.BorderFactory.createTitledBorder("Resources"));

        jLabel7.setText("cores:");

        jLabel8.setText("total physical memory:");

        jLabel9.setText("total swap memory:");

        javax.swing.GroupLayout pnlResourcesLayout = new javax.swing.GroupLayout(pnlResources);
        pnlResources.setLayout(pnlResourcesLayout);
        pnlResourcesLayout.setHorizontalGroup(
            pnlResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResourcesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCores)
                    .addComponent(lblMemory)
                    .addComponent(lblSwapMemory))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        pnlResourcesLayout.setVerticalGroup(
            pnlResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResourcesLayout.createSequentialGroup()
                .addGroup(pnlResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblCores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblMemory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblSwapMemory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEnvironment.setBorder(javax.swing.BorderFactory.createTitledBorder("Environment"));

        jLabel10.setText("username:");

        jLabel11.setText("user home directory:");

        jLabel12.setText("current working directory:");

        javax.swing.GroupLayout pnlEnvironmentLayout = new javax.swing.GroupLayout(pnlEnvironment);
        pnlEnvironment.setLayout(pnlEnvironmentLayout);
        pnlEnvironmentLayout.setHorizontalGroup(
            pnlEnvironmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnvironmentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnvironmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnvironmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName)
                    .addComponent(lblHomeDir)
                    .addComponent(lblWorkingDir))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        pnlEnvironmentLayout.setVerticalGroup(
            pnlEnvironmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnvironmentLayout.createSequentialGroup()
                .addGroup(pnlEnvironmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnvironmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblHomeDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnvironmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblWorkingDir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlResources, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEnvironment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEnvironment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCores;
    private javax.swing.JLabel lblHomeDir;
    private javax.swing.JLabel lblMemory;
    private javax.swing.JLabel lblOSArch;
    private javax.swing.JLabel lblOSName;
    private javax.swing.JLabel lblOSVersion;
    private javax.swing.JLabel lblSwapMemory;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblWorkingDir;
    private javax.swing.JPanel pnlEnvironment;
    private javax.swing.JPanel pnlOS;
    private javax.swing.JPanel pnlResources;
    // End of variables declaration//GEN-END:variables
}
